# docker network create --driver bridge go_hexa_net
# docker build -t go_kafka_producer . -f dockerfile-producer
# docker run -dit --network go_hexa_net --name go_kafka_consumer

FROM golang:1.17 As builder
WORKDIR /app

COPY . .
WORKDIR /app/go-kafka/cmd/producer
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w' -o go_kafka_producer

FROM scratch
WORKDIR /app
COPY --from=builder /app/go-kafka/cmd/producer/go_kafka_producer .
CMD ["/app/go_kafka_producer"]