# docker network create --driver bridge go_hexa_net
# docker build -t go_kafka_consumer . -f dockerfile-consumer
# docker run -dit --network go_hexa_net --name go_kafka_consumer

FROM golang:1.17 As builder

WORKDIR /app
COPY . .
WORKDIR /app/go-kafka/cmd/producer

RUN echo $(ls -1 /app/go-kafka/cmd/producer)

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-w' -o go_kafka_consumer

FROM scratch
WORKDIR /app
COPY --from=builder /app/go-kafka/cmd/consumer/go_kafka_consumer .
CMD ["/app/go_kafka_consumer"]