kafkaConfig:
  username: admin
  password: admin
  clientid: GO-CLIENT-MESSAGE
  brokers1: 127.0.0.1:9091
  brokers2: 127.0.0.1:9092
  brokers3: 127.0.0.1:9093
  groupid: GROUP-01
  topic: LOJA_NOVO_PEDIDO
  partition: 3
  replicationfactor: 3
  lag: 10