kafkaConfig:
  username: admin
  password: admin
  clientid: GO-CLIENT-MESSAGE
  brokers1: b-1.msk-cluster-vpc-east2.xsf10f.c3.kafka.us-east-2.amazonaws.com:9092
  brokers2: b-2.msk-cluster-vpc-east2.xsf10f.c3.kafka.us-east-2.amazonaws.com:9092
  brokers3: b-1.msk-cluster-vpc-east2.xsf10f.c3.kafka.us-east-2.amazonaws.com:9092
  groupid: GROUP-02
  topic: LOJA_NOVO_PEDIDO_02
  partition: 4
  replicationfactor: 2
  lag: 10