kafkaConfig:
  username: admin
  password: admin
  clientid: GO-CLIENT-MESSAGE
  brokers1: 127.0.0.1:9099
  brokers2: 127.0.0.1:9099
  brokers3: 127.0.0.1:9099
  groupid: GROUP-01
  topic: LOJA_NOVO_PEDIDO
  partition: 3
  replicationfactor: 1
  lag: 10